### ISSUE TITLE
admin can't edit.

### ISSUE THREAD

**Issue by mlotfi2005** [philipsorst/angular-rest-springsecurity#18]
Hi,
Thanks for this tutorial,

when run this project inside eclipse IDE the edit and delete links disappear.

Can you please tell me where is the start point of this project, I looked for a welcome file or a default controller, but could not understand how this rest project start.
thanks, your help is appreciated.

**Comment by mlotfi2005** [comment]
when run it inside eclipse IDE you can't see the edit links, but when I run it from chrome browser I can see them now.
thanks.

**Comment by philipsorst** [comment]
Hi.

This is a Spring based application, so you should have a look at ``src/main/resources/context.xml``, this is where the backend application is configured. As this is currently not a tutorial, but rather a simple example application, I suggest you have a look at the documentation of the used technologies. They are linked in the README file.

Kind regards,

Philip
