### ISSUE TITLE
How to migrate spring security 4

### ISSUE THREAD

**Issue by thekowsar** [philipsorst/angular-rest-springsecurity#27]
I have to update JDK 7 to 8. For this need to update spring frame work 3 to 4 as well security.
I have update all spring jar to 4.0.0.RELEASE but can't login.

Thank for help.

**Comment by philipsorst** [comment]
Hi, I just upgraded the whole project to Spring4, have a look at the linked commit above.

**Comment by thekowsar** [comment]
Thanks a lot.
