### ISSUE TITLE
I need the database sturcture please

### ISSUE THREAD

**Issue by belalothman** [philipsorst/angular-rest-springsecurity#31]
thank you for this wonderfull application

if I want to work with real database, can you show me the database sturctur please

**Comment by philipsorst** [comment]
Hi, glad you like the project. As the project is based on Hibernate/JPA it is actually database agnostic. If you want to change the underlying database, you can do so by including the required driver in the `pom.xml` and setting the required parameters in `src/main/resources/application.properties`. The database structure is automatically generated when you run the application.
