### ISSUE TITLE
Could you please provide the database file?

### ISSUE THREAD

**Issue by Eainde** [philipsorst/angular-rest-springsecurity#33]

**Comment by philipsorst** [comment]
Hi, what exactly do you mean by "database file"?

**Comment by gaoobin** [comment]
could you please provide the sql file.create tables and insert needed data sql

**Comment by malikme3** [comment]
Also what is user and password to login ?

**Comment by philipsorst** [comment]
There is no explicit schema file as the Schema is implicitly defined via JPA annotations. It is automatically deployed during the startup of the application, in our case to the in memory HSQLDB. The database is then populated with the example data as provided in the  `DataBaseInitializer`.
There are two users: 'user' with password 'user' and 'admin' with password 'admin'.
